import { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Helmets & Safety Gear',
    name_bn: 'হেলমেট ও সেফটি গিয়ার',
    slug: 'helmets-safety-gear',
    description: 'Full face, half face, and open face helmets with safety gear',
    display_order: 1,
    is_active: true,
  },
  {
    id: '2',
    name: 'Parts & Modifications',
    name_bn: 'পার্টস ও মডিফিকেশন',
    slug: 'parts-modifications',
    description: 'Engine parts, exhaust, lights, mirrors and more',
    display_order: 2,
    is_active: true,
  },
  {
    id: '3',
    name: 'Accessories',
    name_bn: 'এক্সেসরিজ',
    slug: 'accessories',
    description: 'Mobile holders, bags, covers, locks and accessories',
    display_order: 3,
    is_active: true,
  },
  {
    id: '4',
    name: 'Maintenance & Tools',
    name_bn: 'মেইনটেনেন্স ও টুলস',
    slug: 'maintenance-tools',
    description: 'Engine oil, cleaners, tool kits and maintenance supplies',
    display_order: 4,
    is_active: true,
  },
  {
    id: '5',
    name: 'Riding Gear',
    name_bn: 'রাইডিং গিয়ার',
    slug: 'riding-gear',
    description: 'Gloves, boots, pants, jerseys and riding apparel',
    display_order: 5,
    is_active: true,
  },
  {
    id: '6',
    name: 'Body Parts',
    name_bn: 'বডি পার্টস',
    slug: 'body-parts',
    description: 'Fairings, tanks, mudguards, seats and body components',
    display_order: 6,
    is_active: true,
  },
  {
    id: '7',
    name: 'Electronics',
    name_bn: 'ইলেকট্রনিক্স',
    slug: 'electronics',
    description: 'GPS, action cameras, Bluetooth speakers and electronics',
    display_order: 7,
    is_active: true,
  },
];

export const products: Product[] = [
  // Helmets & Safety Gear
  {
    id: '1',
    name: 'LS2 FF320 Full Face Helmet',
    name_bn: 'LS2 FF320 ফুল ফেস হেলমেট',
    slug: 'ls2-ff320-full-face-helmet',
    description: 'Premium full face helmet with aerodynamic shell, dual visor system, and excellent ventilation. DOT approved for maximum safety. Perfect for highway and track riding.',
    category_id: '1',
    brand: 'LS2',
    price: 8500,
    sale_price: 7500,
    stock_quantity: 25,
    sku: 'LS2-FF320-BLK',
    images: ['/images/helmet-1.jpg'],
    specifications: {
      'Shell Material': 'High Pressure Thermoplastic',
      'Weight': '1350g ± 50g',
      'Certification': 'DOT, ECE',
      'Visor': 'Anti-scratch, UV Protection',
      'Ventilation': '4 Intake, 2 Exhaust vents',
    },
    is_featured: true,
    is_active: true,
    views_count: 1250,
    sales_count: 89,
    rating: 4.5,
    review_count: 45,
  },
  {
    id: '2',
    name: 'Studds Thunder D1 Helmet',
    name_bn: 'স্টাডস থান্ডার D1 হেলমেট',
    slug: 'studds-thunder-d1-helmet',
    description: 'Lightweight open face helmet perfect for city riding. ISI certified with comfortable padding and multiple color options. Popular choice among commuters.',
    category_id: '1',
    brand: 'Studds',
    price: 2500,
    stock_quantity: 50,
    sku: 'STD-THD1-RED',
    images: ['/images/helmet-2.jpg'],
    specifications: {
      'Shell Material': 'Thermoplastic',
      'Weight': '850g',
      'Certification': 'ISI',
      'Type': 'Open Face',
      'Liner': 'Removable, Washable',
    },
    is_featured: false,
    is_active: true,
    views_count: 890,
    sales_count: 156,
    rating: 4.2,
    review_count: 78,
  },
  {
    id: '20',
    name: 'AGV K3 SV Full Face Helmet',
    name_bn: 'AGV K3 SV ফুল ফেস হেলমেট',
    slug: 'agv-k3-sv-helmet',
    description: 'Italian design racing helmet with superior aerodynamics. Lightweight composite shell, Pinlock ready visor, and racing fit for serious riders.',
    category_id: '1',
    brand: 'AGV',
    price: 15500,
    sale_price: 13999,
    stock_quantity: 12,
    sku: 'AGV-K3SV-BLK',
    images: ['/images/agv-helmet.jpg'],
    specifications: {
      'Shell Material': 'Fiberglass Composite',
      'Weight': '1250g',
      'Certification': 'ECE, DOT',
      'Visor': 'Pinlock Ready, Anti-fog',
      'Sizes': 'XS to XXL',
    },
    is_featured: true,
    is_active: true,
    views_count: 890,
    sales_count: 45,
    rating: 4.8,
    review_count: 67,
  },
  {
    id: '21',
    name: 'Axor Apex Venomous Open Face',
    name_bn: 'এক্সর এপেক্স ভেনোমাস ওপেন ফেস',
    slug: 'axor-apex-venomous',
    description: 'Stylish open face helmet with graphic designs. Popular among young riders. ISI certified with good ventilation system.',
    category_id: '1',
    brand: 'Axor',
    price: 3200,
    sale_price: 2850,
    stock_quantity: 40,
    sku: 'AXOR-APEX-VNM',
    images: ['/images/axor-helmet.jpg'],
    specifications: {
      'Shell Material': 'Thermoplastic',
      'Weight': '900g',
      'Certification': 'ISI',
      'Design': 'Graphic Print',
      'Padding': 'Soft, Breathable',
    },
    is_featured: false,
    is_active: true,
    views_count: 670,
    sales_count: 123,
    rating: 4.0,
    review_count: 56,
  },
  {
    id: '22',
    name: 'Knee & Elbow Guard Set',
    name_bn: 'হাঁটু ও কনুই গার্ড সেট',
    slug: 'knee-elbow-guard-set',
    description: 'Professional grade knee and elbow protection set. Hard shell design with adjustable straps. Essential for off-road and sports riding.',
    category_id: '1',
    brand: 'Fox Racing',
    price: 4500,
    sale_price: 3800,
    stock_quantity: 30,
    sku: 'FOX-KE-SET',
    images: ['/images/knee-guard.jpg'],
    specifications: {
      'Material': 'Hard Plastic Shell with foam padding',
      'Adjustable': 'Yes, Multiple straps',
      'Size': 'Universal fit',
      'Protection Level': 'CE Certified',
    },
    is_featured: false,
    is_active: true,
    views_count: 450,
    sales_count: 67,
    rating: 4.6,
    review_count: 34,
  },

  // Parts & Modifications
  {
    id: '3',
    name: 'LED Headlight Bulb H4',
    name_bn: 'LED হেডলাইট বাল্ব H4',
    slug: 'led-headlight-h4',
    description: 'Super bright LED headlight bulb with 6000K white light. 360° adjustable beam, plug and play installation for all bikes. Significantly improves night visibility.',
    category_id: '2',
    brand: 'AutoVision',
    price: 1200,
    sale_price: 999,
    stock_quantity: 100,
    sku: 'LED-H4-6K',
    images: ['/images/led-light.jpg'],
    specifications: {
      'Power': '35W',
      'Voltage': '12V DC',
      'Color Temperature': '6000K',
      'Lifespan': '50,000 hours',
      'Lumens': '3000LM',
    },
    is_featured: true,
    is_active: true,
    views_count: 2100,
    sales_count: 234,
    rating: 4.7,
    review_count: 112,
  },
  {
    id: '8',
    name: 'Racing Exhaust Pipe',
    name_bn: 'রেসিং এক্সস্ট পাইপ',
    slug: 'racing-exhaust-pipe',
    description: 'Universal racing exhaust for 150-200cc bikes. Stainless steel construction, deep aggressive sound, improved performance and fuel efficiency.',
    category_id: '2',
    brand: 'Akrapovic Style',
    price: 4500,
    sale_price: 3800,
    stock_quantity: 15,
    sku: 'EXH-RAC-SS',
    images: ['/images/exhaust.jpg'],
    specifications: {
      'Material': 'Stainless Steel',
      'Fitment': 'Universal (150-200cc)',
      'Length': '420mm',
      'Diameter': '51mm',
      'Finish': 'Polished Silver',
    },
    is_featured: true,
    is_active: true,
    views_count: 1890,
    sales_count: 67,
    rating: 4.6,
    review_count: 43,
  },
  {
    id: '23',
    name: 'LED Tail Light Strip',
    name_bn: 'LED টেইল লাইট স্ট্রিপ',
    slug: 'led-tail-light-strip',
    description: 'Flexible LED tail light strip with brake light function. Easy installation, waterproof design. Adds modern look to any bike.',
    category_id: '2',
    brand: 'GenericPro',
    price: 850,
    sale_price: 699,
    stock_quantity: 80,
    sku: 'LED-TAIL-STRIP',
    images: ['/images/tail-light.jpg'],
    specifications: {
      'Length': '32cm flexible strip',
      'Color': 'Red with amber turn signals',
      'Waterproof': 'IP67 rated',
      'Voltage': '12V DC',
      'Installation': 'Self-adhesive tape',
    },
    is_featured: false,
    is_active: true,
    views_count: 1230,
    sales_count: 178,
    rating: 4.4,
    review_count: 92,
  },
  {
    id: '24',
    name: 'Bar End Mirror Set',
    name_bn: 'বার এন্ড মিরর সেট',
    slug: 'bar-end-mirror-set',
    description: 'Premium CNC machined bar end mirrors. 360° adjustable, convex glass for wide view. Fits all standard handlebar bikes.',
    category_id: '2',
    brand: 'RizomaPro',
    price: 2800,
    sale_price: 2400,
    stock_quantity: 45,
    sku: 'MIR-BAR-CNC',
    images: ['/images/bar-mirror.jpg'],
    specifications: {
      'Material': 'CNC Aluminum',
      'Mirror Type': 'Convex Glass',
      'Fitment': 'Universal (Standard bars)',
      'Color Options': 'Black, Silver, Gold',
      'Thread Size': '14mm to 18mm adapters included',
    },
    is_featured: false,
    is_active: true,
    views_count: 780,
    sales_count: 89,
    rating: 4.5,
    review_count: 45,
  },
  {
    id: '25',
    name: 'Engine Guard Crash Bar',
    name_bn: 'ইঞ্জিন গার্ড ক্র্যাশ বার',
    slug: 'engine-guard-crash-bar',
    description: 'Heavy duty engine protection crash bar. Prevents engine damage during falls. Powder coated finish, easy bolt-on installation.',
    category_id: '2',
    brand: 'AutoGuard',
    price: 3500,
    stock_quantity: 20,
    sku: 'ENGGUARD-22',
    images: ['/images/crash-bar.jpg'],
    specifications: {
      'Material': '22mm Steel Tube',
      'Finish': 'Black Powder Coat',
      'Fitment': 'Model Specific (Yamaha FZ, Pulsar, Apache)',
      'Weight': '2.5kg per pair',
      'Mounting': 'Bolt-on, Hardware included',
    },
    is_featured: false,
    is_active: true,
    views_count: 950,
    sales_count: 56,
    rating: 4.7,
    review_count: 38,
  },

  // Accessories
  {
    id: '4',
    name: 'Mobile Phone Holder',
    name_bn: 'মোবাইল ফোন হোল্ডার',
    slug: 'mobile-phone-holder',
    description: 'Universal bike mobile holder with 360° rotation. Strong grip, shock-proof design, fits all phone sizes up to 6.5 inches. Essential for navigation.',
    category_id: '3',
    brand: 'RockBros',
    price: 450,
    sale_price: 350,
    stock_quantity: 75,
    sku: 'MOB-HLDR-360',
    images: ['/images/mobile-holder.jpg'],
    specifications: {
      'Material': 'ABS Plastic + Aluminum',
      'Phone Size': 'Up to 6.5 inches',
      'Rotation': '360 degrees',
      'Mount Type': 'Handlebar',
      'Grip Type': '4-point secure grip',
    },
    is_featured: false,
    is_active: true,
    views_count: 1560,
    sales_count: 298,
    rating: 4.3,
    review_count: 89,
  },
  {
    id: '7',
    name: 'Bike Cover Waterproof XXL',
    name_bn: 'বাইক কভার ওয়াটারপ্রুফ XXL',
    slug: 'bike-cover-waterproof-xxl',
    description: 'Heavy duty waterproof bike cover with lock holes. UV resistant, fits all bikes up to 250cc. Protects from rain, dust and sun. Includes carry bag.',
    category_id: '3',
    brand: 'MotoCare',
    price: 800,
    sale_price: 650,
    stock_quantity: 85,
    sku: 'CVR-XXL-BLK',
    images: ['/images/bike-cover.jpg'],
    specifications: {
      'Material': '190T Polyester',
      'Size': 'XXL (230cm x 100cm x 125cm)',
      'Features': 'Waterproof, UV Resistant',
      'Includes': 'Carry Bag, Lock Holes',
      'Color': 'Black with reflective strips',
    },
    is_featured: false,
    is_active: true,
    views_count: 1120,
    sales_count: 203,
    rating: 4.1,
    review_count: 67,
  },
  {
    id: '26',
    name: 'Tank Bag Magnetic',
    name_bn: 'ট্যাঙ্ক ব্যাগ ম্যাগনেটিক',
    slug: 'tank-bag-magnetic',
    description: 'Expandable magnetic tank bag with transparent map pocket. Water resistant, perfect for long rides and touring.',
    category_id: '3',
    brand: 'GIVI',
    price: 3200,
    sale_price: 2850,
    stock_quantity: 25,
    sku: 'TANKBAG-MAG',
    images: ['/images/tank-bag.jpg'],
    specifications: {
      'Capacity': '14-18 Liters expandable',
      'Material': 'Water resistant nylon',
      'Mounting': '4 strong magnets',
      'Pockets': 'Top transparent pocket, side pockets',
      'Compatibility': 'Metal fuel tanks only',
    },
    is_featured: false,
    is_active: true,
    views_count: 680,
    sales_count: 45,
    rating: 4.5,
    review_count: 28,
  },
  {
    id: '27',
    name: 'Tail Box 32 Liter',
    name_bn: 'টেইল বক্স ৩২ লিটার',
    slug: 'tail-box-32-liter',
    description: 'Large capacity top box with universal mounting plate. Fits 1 full face helmet. Includes 2 keys and mounting hardware.',
    category_id: '3',
    brand: 'Studds',
    price: 4200,
    sale_price: 3699,
    stock_quantity: 18,
    sku: 'TAILBOX-32L',
    images: ['/images/tail-box.jpg'],
    specifications: {
      'Capacity': '32 Liters',
      'Helmet Capacity': '1 Full Face',
      'Material': 'High Impact ABS',
      'Lock': 'Key lock system (2 keys)',
      'Mounting': 'Universal plate included',
    },
    is_featured: true,
    is_active: true,
    views_count: 1450,
    sales_count: 89,
    rating: 4.6,
    review_count: 72,
  },
  {
    id: '28',
    name: 'USB Charger Socket 2-Port',
    name_bn: 'USB চার্জার সকেট ২-পোর্ট',
    slug: 'usb-charger-2-port',
    description: 'Waterproof dual USB charger socket for motorcycles. Fast charging 2.4A output. LED indicator and on/off switch.',
    category_id: '3',
    brand: 'AutoCharge',
    price: 650,
    sale_price: 499,
    stock_quantity: 95,
    sku: 'USB-CHRG-2P',
    images: ['/images/usb-charger.jpg'],
    specifications: {
      'Ports': '2 USB Ports',
      'Output': '5V 2.4A per port',
      'Waterproof': 'IP66 rated with cap',
      'Input Voltage': '12V DC',
      'Features': 'LED indicator, On/Off switch',
    },
    is_featured: false,
    is_active: true,
    views_count: 1890,
    sales_count: 267,
    rating: 4.4,
    review_count: 134,
  },
  {
    id: '29',
    name: 'Chain Lock Heavy Duty',
    name_bn: 'চেইন লক হেভি ডিউটি',
    slug: 'chain-lock-heavy-duty',
    description: 'Security chain lock with hardened steel links. 1.2 meter length, weather resistant. Includes 3 keys.',
    category_id: '3',
    brand: 'SecureLock',
    price: 2200,
    sale_price: 1850,
    stock_quantity: 55,
    sku: 'CHNLCK-HD',
    images: ['/images/chain-lock.jpg'],
    specifications: {
      'Material': 'Hardened Steel Chain',
      'Length': '120cm',
      'Link Diameter': '10mm',
      'Lock Type': 'Disc Lock',
      'Keys': '3 keys included',
    },
    is_featured: false,
    is_active: true,
    views_count: 1120,
    sales_count: 145,
    rating: 4.7,
    review_count: 89,
  },

  // Maintenance & Tools
  {
    id: '5',
    name: 'Motul 7100 Engine Oil 10W40',
    name_bn: 'মোটুল 7100 ইঞ্জিন অয়েল 10W40',
    slug: 'motul-7100-engine-oil',
    description: '100% synthetic engine oil for 4-stroke motorcycles. Provides excellent protection and smooth gear shifting. Recommended for high performance bikes.',
    category_id: '4',
    brand: 'Motul',
    price: 1800,
    stock_quantity: 60,
    sku: 'MTL-7100-1L',
    images: ['/images/engine-oil.jpg'],
    specifications: {
      'Volume': '1 Liter',
      'Viscosity': '10W40',
      'Type': '100% Synthetic',
      'Standards': 'JASO MA2, API SN',
      'Suitable For': 'All 4-stroke bikes',
    },
    is_featured: true,
    is_active: true,
    views_count: 980,
    sales_count: 187,
    rating: 4.8,
    review_count: 156,
  },
  {
    id: '30',
    name: 'Shell Advance AX7 10W40',
    name_bn: 'শেল এডভান্স AX7 10W40',
    slug: 'shell-advance-ax7',
    description: 'Semi-synthetic engine oil with advanced protection. Popular choice for commuter bikes. Reduces engine noise and wear.',
    category_id: '4',
    brand: 'Shell',
    price: 950,
    sale_price: 850,
    stock_quantity: 100,
    sku: 'SHELL-AX7-1L',
    images: ['/images/shell-oil.jpg'],
    specifications: {
      'Volume': '1 Liter',
      'Viscosity': '10W40',
      'Type': 'Semi-Synthetic',
      'Standards': 'JASO MA2',
      'Ideal For': 'Daily commute bikes',
    },
    is_featured: false,
    is_active: true,
    views_count: 1560,
    sales_count: 289,
    rating: 4.5,
    review_count: 178,
  },
  {
    id: '31',
    name: 'Bike Cleaning Kit Pro',
    name_bn: 'বাইক ক্লিনিং কিট প্রো',
    slug: 'bike-cleaning-kit-pro',
    description: 'Complete bike cleaning kit with shampoo, wax, chain cleaner, microfiber cloths and brushes. Everything you need for professional cleaning.',
    category_id: '4',
    brand: 'Muc-Off',
    price: 2500,
    sale_price: 2199,
    stock_quantity: 35,
    sku: 'CLEAN-KIT-PRO',
    images: ['/images/cleaning-kit.jpg'],
    specifications: {
      'Includes': 'Shampoo 500ml, Wax 500ml, Chain cleaner',
      'Accessories': '3 Brushes, 2 Microfiber cloths',
      'Formula': 'Biodegradable, Safe for all surfaces',
      'Coverage': 'Multiple washes',
    },
    is_featured: false,
    is_active: true,
    views_count: 670,
    sales_count: 112,
    rating: 4.6,
    review_count: 67,
  },
  {
    id: '32',
    name: 'Multi Tool Kit 16 in 1',
    name_bn: 'মাল্টি টুল কিট ১৬ ইন ১',
    slug: 'multi-tool-kit-16in1',
    description: 'Compact 16-in-1 motorcycle tool kit. Includes hex keys, screwdrivers, wrenches. Perfect for emergency repairs on the road.',
    category_id: '4',
    brand: 'CruzTools',
    price: 1500,
    sale_price: 1299,
    stock_quantity: 50,
    sku: 'TOOL-16IN1',
    images: ['/images/tool-kit.jpg'],
    specifications: {
      'Tools': '16 different tools',
      'Includes': 'Hex keys, Phillips, Flathead, Wrenches',
      'Material': 'Chrome Vanadium Steel',
      'Compact': 'Foldable design with carry case',
      'Weight': '350g',
    },
    is_featured: false,
    is_active: true,
    views_count: 890,
    sales_count: 156,
    rating: 4.7,
    review_count: 98,
  },
  {
    id: '33',
    name: 'Chain Lubricant Spray',
    name_bn: 'চেইন লুব্রিকেন্ট স্প্রে',
    slug: 'chain-lubricant-spray',
    description: 'Premium chain lube spray with PTFE. Long lasting, water resistant. Reduces chain wear and noise significantly.',
    category_id: '4',
    brand: 'Motul',
    price: 650,
    sale_price: 550,
    stock_quantity: 120,
    sku: 'CHNLUBE-SPRAY',
    images: ['/images/chain-lube.jpg'],
    specifications: {
      'Volume': '400ml',
      'Formula': 'PTFE based',
      'Properties': 'Water resistant, Long lasting',
      'Application': 'Spray nozzle',
      'Coverage': 'Approx 15-20 applications',
    },
    is_featured: false,
    is_active: true,
    views_count: 1340,
    sales_count: 234,
    rating: 4.5,
    review_count: 145,
  },

  // Riding Gear
  {
    id: '6',
    name: 'Riding Gloves Pro',
    name_bn: 'রাইডিং গ্লাভস প্রো',
    slug: 'riding-gloves-pro',
    description: 'Professional riding gloves with knuckle protection, touchscreen compatible, and breathable fabric for all-season use. CE certified protection.',
    category_id: '5',
    brand: 'Scoyco',
    price: 1500,
    sale_price: 1200,
    stock_quantity: 40,
    sku: 'GLV-PRO-BLK-L',
    images: ['/images/gloves.jpg'],
    specifications: {
      'Material': 'Leather + Mesh',
      'Protection': 'Hard Knuckle + CE certified',
      'Sizes': 'M, L, XL',
      'Features': 'Touchscreen Compatible',
      'Season': 'All season use',
    },
    is_featured: false,
    is_active: true,
    views_count: 670,
    sales_count: 92,
    rating: 4.4,
    review_count: 34,
  },
  {
    id: '34',
    name: 'Riding Jacket Waterproof',
    name_bn: 'রাইডিং জ্যাকেট ওয়াটারপ্রুফ',
    slug: 'riding-jacket-waterproof',
    description: 'Full body protection riding jacket with CE armor. Waterproof and breathable. Removable thermal liner for all weather riding.',
    category_id: '5',
    brand: 'Alpinestars',
    price: 12500,
    sale_price: 10999,
    stock_quantity: 15,
    sku: 'JACKET-WP-BLK',
    images: ['/images/riding-jacket.jpg'],
    specifications: {
      'Material': 'Cordura fabric with waterproof membrane',
      'Protection': 'CE certified armor (Shoulders, Elbows, Back)',
      'Sizes': 'S, M, L, XL, XXL',
      'Features': 'Removable thermal liner, Ventilation zips',
      'Reflective': 'High-vis reflective panels',
    },
    is_featured: true,
    is_active: true,
    views_count: 1120,
    sales_count: 56,
    rating: 4.8,
    review_count: 45,
  },
  {
    id: '35',
    name: 'Riding Pants Kevlar',
    name_bn: 'রাইডিং প্যান্ট কেভলার',
    slug: 'riding-pants-kevlar',
    description: 'Motorcycle jeans with Kevlar lining and CE knee armor. Looks casual but provides serious protection. Comfortable for daily wear.',
    category_id: '5',
    brand: 'Royal Enfield',
    price: 6500,
    sale_price: 5799,
    stock_quantity: 28,
    sku: 'PANTS-KEV-BLU',
    images: ['/images/riding-pants.jpg'],
    specifications: {
      'Material': 'Denim with Kevlar reinforcement',
      'Protection': 'CE certified knee armor',
      'Sizes': '28, 30, 32, 34, 36',
      'Style': 'Slim fit casual look',
      'Areas Protected': 'Hips, Knees, Seat',
    },
    is_featured: false,
    is_active: true,
    views_count: 780,
    sales_count: 67,
    rating: 4.5,
    review_count: 42,
  },
  {
    id: '36',
    name: 'Riding Boots Leather',
    name_bn: 'রাইডিং বুট লেদার',
    slug: 'riding-boots-leather',
    description: 'Full grain leather motorcycle boots with ankle protection. Oil resistant sole, waterproof construction. Shift pad included.',
    category_id: '5',
    brand: 'Dainese',
    price: 8500,
    sale_price: 7499,
    stock_quantity: 22,
    sku: 'BOOTS-LTHR-BLK',
    images: ['/images/riding-boots.jpg'],
    specifications: {
      'Material': 'Full grain leather',
      'Protection': 'Reinforced ankle, toe, heel',
      'Sizes': 'UK 7 to 11',
      'Sole': 'Oil resistant, Anti-slip',
      'Features': 'Waterproof, Shift pad',
    },
    is_featured: false,
    is_active: true,
    views_count: 650,
    sales_count: 45,
    rating: 4.7,
    review_count: 34,
  },
  {
    id: '37',
    name: 'Balaclava Face Mask',
    name_bn: 'বালাক্লাভা ফেস মাস্ক',
    slug: 'balaclava-face-mask',
    description: 'Breathable balaclava for all weather riding. Protects from dust, sun and cold. Quick dry fabric, fits under any helmet.',
    category_id: '5',
    brand: 'Wildcraft',
    price: 450,
    sale_price: 350,
    stock_quantity: 100,
    sku: 'BALA-BLK',
    images: ['/images/balaclava.jpg'],
    specifications: {
      'Material': 'Polyester spandex blend',
      'Size': 'One size fits all',
      'Features': 'Breathable, Quick dry',
      'Protection': 'UV protection, Dust filter',
      'Colors': 'Black, Grey, Camo',
    },
    is_featured: false,
    is_active: true,
    views_count: 1450,
    sales_count: 312,
    rating: 4.3,
    review_count: 178,
  },

  // Body Parts
  {
    id: '38',
    name: 'Side View Mirror Sports Style',
    name_bn: 'সাইড ভিউ মিরর স্পোর্টস স্টাইল',
    slug: 'side-mirror-sports',
    description: 'Aerodynamic sports style side mirrors. CNC machined aluminum body. Universal fitment with multiple adapters.',
    category_id: '6',
    brand: 'KTM Style',
    price: 1800,
    sale_price: 1499,
    stock_quantity: 60,
    sku: 'MIR-SPORT-CNC',
    images: ['/images/sport-mirror.jpg'],
    specifications: {
      'Material': 'CNC Aluminum body',
      'Mirror': 'Convex glass',
      'Finish': 'Anodized (Black, Silver, Orange)',
      'Fitment': 'Universal with adapters',
      'Sold As': 'Pair',
    },
    is_featured: false,
    is_active: true,
    views_count: 890,
    sales_count: 134,
    rating: 4.4,
    review_count: 67,
  },
  {
    id: '39',
    name: 'Handlebar Grip Set',
    name_bn: 'হ্যান্ডেলবার গ্রিপ সেট',
    slug: 'handlebar-grip-set',
    description: 'Soft rubber handlebar grips with anti-slip pattern. Comfortable for long rides. Easy installation. Available in multiple colors.',
    category_id: '6',
    brand: 'ProGrip',
    price: 550,
    sale_price: 450,
    stock_quantity: 80,
    sku: 'GRIP-SOFT-BLK',
    images: ['/images/handlebar-grip.jpg'],
    specifications: {
      'Material': 'Soft compound rubber',
      'Length': '12cm',
      'Diameter': '22mm (7/8 inch)',
      'Pattern': 'Anti-slip diamond pattern',
      'Colors': 'Black, Red, Blue, Orange',
    },
    is_featured: false,
    is_active: true,
    views_count: 1240,
    sales_count: 198,
    rating: 4.2,
    review_count: 89,
  },
  {
    id: '40',
    name: 'Fuel Tank Pad Protector',
    name_bn: 'ফুয়েল ট্যাঙ্ক প্যাড প্রোটেক্টর',
    slug: 'tank-pad-protector',
    description: 'Carbon fiber pattern tank pad. Protects tank from scratches. Self-adhesive 3M backing. Universal design fits most tanks.',
    category_id: '6',
    brand: 'Universal',
    price: 350,
    sale_price: 280,
    stock_quantity: 120,
    sku: 'TANKPAD-CF',
    images: ['/images/tank-pad.jpg'],
    specifications: {
      'Material': 'Polyurethane with carbon fiber pattern',
      'Size': '23cm x 18cm',
      'Adhesive': '3M backing',
      'Design': 'Universal fit',
      'Finish': 'Glossy carbon look',
    },
    is_featured: false,
    is_active: true,
    views_count: 980,
    sales_count: 167,
    rating: 4.3,
    review_count: 76,
  },

  // Electronics
  {
    id: '41',
    name: 'Action Camera 4K',
    name_bn: 'অ্যাকশন ক্যামেরা 4K',
    slug: 'action-camera-4k',
    description: 'Waterproof 4K action camera for helmet mounting. Record your rides in ultra HD. Includes multiple mounts and accessories.',
    category_id: '7',
    brand: 'GoPro Style',
    price: 8500,
    sale_price: 7299,
    stock_quantity: 18,
    sku: 'CAM-4K-PRO',
    images: ['/images/action-cam.jpg'],
    specifications: {
      'Resolution': '4K 30fps, 1080p 60fps',
      'Screen': '2 inch touch display',
      'Waterproof': 'Up to 30m without case',
      'Battery': '1200mAh, 90 mins recording',
      'Includes': 'Helmet mount, handlebar mount, accessories',
    },
    is_featured: true,
    is_active: true,
    views_count: 1560,
    sales_count: 78,
    rating: 4.6,
    review_count: 56,
  },
  {
    id: '42',
    name: 'Bluetooth Speaker Handlebar',
    name_bn: 'ব্লুটুথ স্পিকার হ্যান্ডেলবার',
    slug: 'bluetooth-speaker-handlebar',
    description: 'Waterproof Bluetooth speaker mounts on handlebar. Loud clear sound even at high speed. FM radio and hands-free calling.',
    category_id: '7',
    brand: 'Lexin',
    price: 3500,
    sale_price: 2999,
    stock_quantity: 35,
    sku: 'SPKR-BT-WP',
    images: ['/images/bt-speaker.jpg'],
    specifications: {
      'Bluetooth': '5.0',
      'Battery': '2000mAh, 10 hours playback',
      'Waterproof': 'IPX6 rated',
      'Features': 'FM radio, Hands-free calling',
      'Mounting': 'Universal handlebar mount',
    },
    is_featured: false,
    is_active: true,
    views_count: 890,
    sales_count: 112,
    rating: 4.4,
    review_count: 67,
  },
  {
    id: '43',
    name: 'GPS Navigator Motorcycle',
    name_bn: 'GPS নেভিগেটর মোটরসাইকেল',
    slug: 'gps-navigator-motorcycle',
    description: 'Motorcycle specific GPS with glove-friendly touchscreen. Waterproof, preloaded Bangladesh maps. Lifetime map updates.',
    category_id: '7',
    brand: 'Garmin Style',
    price: 15500,
    sale_price: 13999,
    stock_quantity: 8,
    sku: 'GPS-MOTO-5',
    images: ['/images/gps-nav.jpg'],
    specifications: {
      'Screen': '5 inch sunlight readable',
      'Maps': 'Preloaded Bangladesh + South Asia',
      'Waterproof': 'IPX7 rated',
      'Features': 'Bluetooth, Traffic alerts, POI',
      'Mount': 'RAM mount included',
    },
    is_featured: false,
    is_active: true,
    views_count: 670,
    sales_count: 34,
    rating: 4.7,
    review_count: 23,
  },
  {
    id: '44',
    name: 'Tire Pressure Monitoring System',
    name_bn: 'টায়ার প্রেসার মনিটরিং সিস্টেম',
    slug: 'tpms-motorcycle',
    description: 'Wireless TPMS with LCD display. Real-time tire pressure and temperature monitoring. Improves safety and fuel efficiency.',
    category_id: '7',
    brand: 'FoboTech',
    price: 4500,
    sale_price: 3799,
    stock_quantity: 22,
    sku: 'TPMS-WIRELESS',
    images: ['/images/tpms.jpg'],
    specifications: {
      'Display': 'LCD with backlight',
      'Sensors': '2 external sensors',
      'Battery': 'Replaceable CR2032',
      'Alerts': 'Visual and audio warnings',
      'Mounting': 'Handlebar or dashboard',
    },
    is_featured: false,
    is_active: true,
    views_count: 560,
    sales_count: 45,
    rating: 4.5,
    review_count: 28,
  },
];
